version: 0.2

phases:
  build:
    commands:
      - echo Entered into build phase....
  post_build:
  commands:
    - echo build completed successfully
artifacts:
  files:
    - target/demo.jar
discard-paths: yes